### ISSUE TITLE
Running Bloben without domain and reverse proxy

### ISSUE THREAD

**Issue by SuberSeb** [nibdo/bloben-calendar#63]
Hello. Thanks for this awesome CalDAV client!

I want run this on my own server without proxy, e.g. only in local network with address like this 192.168.1.1:1234. Is there a way to do this? I set up domain as 192.168.1.1:1234 but service redirecting to 192.168.1.1:80 (which is my server dashboard). Can you help me please?

**Comment by nibdo** [comment]
Hello,

when you start container, by default only requests to port 8081 are going to bloben, so it should not interfere with your service under port 80. Bloben is using port 80 only in scope of internal docker network.

For example you will access calendar like this: http://localhost:8081/calendar/

But if you want to change ports, it is this part bellow in docker-compose -> 8081 to 1234. Then all requests to 1234 will be passed to nginx container. 
```
Bloben:
.............
    ports:
      - '127.0.0.1:8081:80'

```

**Comment by SuberSeb** [comment]
Can you describe how nginx container should be configured? As I can see in docker-compose, there are no nginx container https://github.com/nibdo/bloben-app/blob/production/docker-compose.yml

**Comment by nibdo** [comment]
Nginx container is included, you can find working config which is used here: https://github.com/nibdo/bloben-app/blob/production/nginx/nginx.conf

**Comment by SuberSeb** [comment]
Why you doesn't included nginx in docker compose? There are only app, postgres and redis.

With config that you provided I'm always getting 302 error. Please provide more instructions to use Bloben.

**Comment by nibdo** [comment]
App container actually contains nginx, which serves static sites and proxy to nodejs server (everything from this one container).

 That config file which I shared is just one way, how it could be handled. And similar is for "outside" connection. So for example if your server has nginx, you just need to proxy outside connections to this bloben nginx container with config like this:
 
```
 server {
    server_name bloben.com;
    
location / {
        proxy_pass http://localhost:8081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    	proxy_set_header        X-Real-IP $remote_addr;
    	proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by SuberSeb** [comment]
Thanks. Will try it.
